version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /tmp/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /tmp/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
